name: Build and Release

on:
  push:
    tags:
      - 'v*'

# Add permissions block
permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
        include:
          - os: windows-latest
            asset_name: focus-frame-windows-${{ github.ref_name }}.exe
            asset_path: dist/focus-frame.exe
          - os: macos-latest
            asset_name: focus-frame-macos-${{ github.ref_name }}
            asset_path: dist/focus-frame
          - os: ubuntu-latest
            asset_name: focus-frame-linux-${{ github.ref_name }}
            asset_path: dist/focus-frame

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt

      - name: Build with PyInstaller
        run: pyinstaller --onefile --windowed --name focus-frame src/main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.asset_path }}

  release:
    needs: build
    runs-on: ubuntu-latest
    # Add permissions to release job specifically
    permissions:
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v3

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            focus-frame-windows-${{ github.ref_name }}.exe/focus-frame.exe
            focus-frame-macos-${{ github.ref_name }}/focus-frame
            focus-frame-linux-${{ github.ref_name }}/focus-frame
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
